class UserNotFoundAuthException implements Exception{}
class WrongPasswordAuthException implements Exception{}
class WeakPasswordAuthException implements Exception{}
class EmailAlreadyInUseAuthException implements Exception{}
class InvalidEmailAuthException implements Exception{}
class GenericAuthException implements Exception{}
class UserNotLoggedInAuthException implements Exception{}
class DatabaseAlreadyOpenException implements Exception{}
class UnableToGetDocumentsDirectory implements Exception{}
class DatabaseIsNotOpen implements Exception{}
class CouldNotDeleteUser implements Exception{}
class UserAlreadyExists implements Exception{}
class CouldNotFindUser implements Exception{}
class CouldNotFindNote implements Exception{}
class CouldNotDeleteNote implements Exception{}
class CouldNotUpdateNote implements Exception{}